### ISSUE TITLE
Automated update commits

### ISSUE THREAD

**Issue by averyfreeman** [romandobra/lessbian#1]
This is great

I need to submit a PR for a simple script that automates what you said in this line: 

> If you want to add your apps into your LiveCD, just put 'apt-get' commands in the my-apps.sh file before you run the main script. If you want to have custom autostart commands when the desktop is loaded, just put them in lessbian-autostart.sh

... by combining it with apt upgrade

There might be some headway on debian systems for ostree these days, too, but I think that might require an entire build system and would probs be out of scope for this particular project

I want to do a thing like this but for a hypervisor like ESXi where you run your VM host from a USB drive, preferably with cockpit.  I was thinking of doing it with Alpine at first, but the musl/openrc thing is just too incompatible with Cockpit (I could do it with Webmin, but ... )

But yeah, it wouldn't really be all that hard,. An appliance distro that runs off USB with a web gui, plug and play to make it easy and less vulnerable to attacks, cockpit even has some rudimentary HA capabilities, ZFS is in the package repo, blah, blah ...

**Comment by romandobra** [comment]
Hi
I'm testing a totally new approach now. This time I'm using debootstrap for the initial "base" build, convenient "parts" scripts for the software installs and the [overlayfs](https://github.com/romandobra/stateless-debian) to run it from RAM. Seems it will be very simple to do what you want with it. Going to publish it someday soon.
